language: node_js
sudo: false
node_js:
  - '8'
  - '10'
env:
  - CXX=g++-4.8 CC=gcc-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
      - libzmq3-dev

script:
  - npm run check-package
  - npm run test
  - npm run jshint

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/travis-deploy.sh
    on:
      repo: dashevo/dashcore-node
      tags: true
